import "dotenv/config";
//ai imports from vercel
import { streamText, type ModelMessage } from "ai";

//adapter module to switch between different modal provider -- open ai, claude with same sdk interface.This provide flexibility to change LLM providers without having to rewrite the code
import { openai } from "@ai-sdk/openai";

import { AgentCallbacks } from "../../types.ts";
import { SYSTEM_PROMPT } from "./system/prompt.ts";
import { tools } from "./tools/index.ts";
import { executeTool } from "./executeTools.ts";
import type { ToolCallInfo } from "../types.ts";
//for tracing and testing used Laminar
import { Laminar, getTracer } from "@lmnr-ai/lmnr";
import { filterMessages } from "./system/filterMessages.ts";

const MODAL_NAME = "gpt-5-mini";

Laminar.initialize({
  projectApiKey: process.env.LMNR_PROJECT_API_KEY,
});

export const runAgent = async (
  userMessage: string,
  conversationHistory: ModelMessage[],
  callbacks: AgentCallbacks,
): Promise<ModelMessage[]> => {
  // Filter and check if we need to compact the conversation history before starting
  const workingHistory = filterMessages(conversationHistory);

  const messages: ModelMessage[] = [
    { role: "system", content: SYSTEM_PROMPT },
    ...workingHistory,
    { role: "user", content: userMessage },
  ];

  let fullResponse = "";

  // Safety cap on the agentic loop. The loop only exits when the model stops
  // requesting tool calls; without a bound, a model that keeps emitting tool
  // calls (e.g. a tool repeatedly errors, or the conversation context is
  // corrupted) would spin forever, continuously generating text.
  const MAX_STEPS = 25;
  let step = 0;

  while (step < MAX_STEPS) {
    step++;
    const result = streamText({
      model: openai(MODAL_NAME),
      messages,
      tools,
      experimental_telemetry: {
        isEnabled: true,
        tracer: getTracer(),
      },
    });

    const toolCalls: ToolCallInfo[] = [];
    let currentText = "";
    let streamError: Error | null = null;

    try {
      for await (const chunk of result.fullStream) {
        //A 'text-delta' chunk type indicates that the LLM is generating text and a new token has arrived.
        // This might represent a few characters or letters from a sentence being generated.
        // The token should be appended to the current text variable to build up the full response, and can be rendered to the UI in real-time to show the streaming effect similar to ChatGPT's token-by-token display.
        if (chunk.type === "text-delta") {
          currentText += chunk.text;
          callbacks.onToken(chunk.text);
        }
        if (chunk.type === "tool-call") {
          const input = "input" in chunk ? chunk.input : {};
          toolCalls.push({
            //The tool call ID is generated by the LLM and must be used to reference the specific tool call when responding with results.
            //  When you append a tool call response to the messages array, it must include the exact ID that matches the original tool call generated by the LLM.
            //  If you use an incorrect ID, no ID, or an ID that doesn't match, you'll get an error from the LLM because it cannot match the response to the original request.
            toolCallId: chunk.toolCallId,
            toolName: chunk.toolName,
            args: input as Record<string, unknown>,
          });
          callbacks.onToolCallStart(chunk.toolName, input);
        }
      }
    } catch (err) {
      streamError = err as Error;
      // If we have some text, continue processing
      // Otherwise, rethrow if it's not a "no output" error
      if (!currentText && !streamError.message.includes("No output generated"))
        throw streamError;
    }
    fullResponse += currentText;

    // If stream errored with "no output" and we have no text, try to recover
    if (streamError && !currentText) {
      // Add a fallback response
      fullResponse =
        "I apologize, but I wasn't able to generate a response. Could you please try rephrasing your message?";
      callbacks.onToken(fullResponse);
      break;
    }

    //LLM keep on generating, until it geneartes a message that has a finish reason. Finish reason can essentially be either I am done or the reason I stopped is because I want you to call a tool.

    //await it as its a stream,so wait until the stream is done completely
    const finishReason = await result.finishReason;

    if (finishReason !== "tool-calls" || toolCalls.length === 0) {
      const responseMessages = await result.response;
      //Even though the LLM generates a message, it doesn't remember it unless you put it back into the messages array.
      // If you show the message to the user but don't add it to the array, when the user responds, the LLM won't see its previous message and won't understand the context.
      // The LLM only sees what's in the messages array, regardless of what it previously generated.
      messages.push(...responseMessages.messages);
      break;
    }

    //This is done to let LLM know that it has requested a tool call.
    const responseMessages = await result.response;
    messages.push(...responseMessages.messages);

    for (const tc of toolCalls) {
      const result = await executeTool(tc.toolName, tc.args);
      callbacks.onToolCallEnd(tc.toolName, result);

      //we need to push the result of the toolcall
      messages.push({
        role: "tool",
        content: [
          {
            type: "tool-result",
            toolCallId: tc.toolCallId,
            toolName: tc.toolName,
            output: { type: "text", value: result },
          },
        ],
      });
    }
  }
  callbacks.onComplete(fullResponse);

  return messages;
  // Forcing Laminar to send the events to the server instead of waiting to flush it in batches
  // await Laminar.flush();
};
